/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import DAO.ConectarBanco;
import com.mysql.jdbc.Connection;
import control.ManipulaDados;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Contato;


public class TelaAgenda extends javax.swing.JFrame {
    static Contato c;
    Connection con = ConectarBanco.conectar();
    ManipulaDados man;
    int id ;
 
    public TelaAgenda() {
        initComponents();
        man = new ManipulaDados(con);
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        try {
            List<Contato> contatos = man.listaContatos(c);
            for(Contato c: contatos){
                modelo.addRow(new Object[]{c.getId(),
                                            c.getNome(),
                                            c.getTelefone(),
                                            c.getObjeto()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        idEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Agenda de Contatos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 21, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 127, -1, -1));

        idNome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        idNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNomeActionPerformed(evt);
            }
        });
        jPanel1.add(idNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 124, 365, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 708, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Telefone:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 230, -1, -1));

        idTelefone.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        idTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(idTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 227, 335, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Objeto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 345, -1, -1));

        idEmail.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        idEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmailActionPerformed(evt);
            }
        });
        jPanel1.add(idEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 342, 380, -1));

        tabela.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "Email"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 808, 177));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 710, -1, -1));

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 710, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome, email, telefone;
        nome = idNome.getText();
        objeto = idObjeto.getText();
        telefone = idTelefone.getText();
        
        Contato contato = new Contato(nome, telefone,objeto);
        
        man.cadastrarContato(contato);
        
        JOptionPane.showMessageDialog(null, "Usuário "+nome+" cadastrado!");
        
        atualizaTabela(man);
        
        limparTela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNomeActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int linhaselecionada = tabela.getSelectedRow();
        //peguei as informações de cada item da linha selecionada
        id = Integer.parseInt(tabela.getValueAt(linhaselecionada, 0).toString());
        String nome = tabela.getValueAt(linhaselecionada, 1).toString();
        String telefone = tabela.getValueAt(linhaselecionada, 2).toString();
        String objeto = tabela.getValueAt(linhaselecionada, 3).toString();
        
        idNome.setText(nome);
        idTelefone.setText(telefone);
        idEmail.setText(objeto);
    }//GEN-LAST:event_tabelaMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        Contato contato = new Contato();
        contato.setId(id);
        
        man.excluir(contato);
        atualizaTabela(man);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome, email, telefone;
        nome = idNome.getText();
        objeto = idObjeto.getText();
        telefone = idTelefone.getText();
        
        Contato contato = new Contato(id, nome, telefone,objeto);
                
        man.alterarContato(contato);
        limparTela();
        atualizaTabela(man);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limparTela();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void idEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmailActionPerformed

    private void idTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTelefoneActionPerformed

    public void limparTela(){
        idNome.setText("");
        idObjeto.setText("");
        idTelefone.setText("");
    }
    
    public void atualizaTabela(ManipulaDados m){
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        try {
            List<Contato> contatos = man.listaContatos(c);
            while(modelo.getRowCount()>0){
              modelo.removeRow(0);
            }
            for(Contato c: contatos){
                modelo.addRow(new Object[]{c.getId(),
                                            c.getNome(),
                                            c.getTelefone(),
                                            c.getObjeto()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
                
                
                
            }
        });
    }
    private javax.swing.JTextFilde idObjeto
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JTextField idEmail;
    private javax.swing.JTextField idNome;
    private javax.swing.JTextField idTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
